# Generated by Django 6.0 on 2026-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Cuộc trò chuyện mới', max_length=255),
        ),
    ]
